version: '3'

services:
  php:
    container_name: php
    hostname: php
    networks:
      app_network:
        aliases:
          - php
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
      # php -S 0.0.0.0:7500 public/index.php
    volumes:
      - ./:/framework
    ports:
      - 7500:7500

networks:
  app_network:
    driver: bridge
