version: '3'

services:
  php:
    container_name: php
    hostname: php
    networks:
      app_network:
        aliases:
          - php
    # command: tail -f /dev/null
    command: bash -c "cd / && supervisord -n -c /svcnf/supervisord.conf"
    build:
      context: .  
      dockerfile: dockerfiles/php/Dockerfile
      # php -S 0.0.0.0:7500 public/index.php
    volumes:
      - ./:/framework
      - ./dockerfiles/php/supervisord.conf:/svcnf/supervisord.conf
    ports:
      - 7400:7500

  compiler:
    container_name: compiler
    hostname: compiler
    networks:
      app_network:
        aliases:
          - compiler
    command: bash -c "cd / && supervisord -n -c /svcnf/supervisord.conf"
    # command: bash -c "cd /framework && npm install && npx -v && npx tailwindcss -i ./resources/styles/main.css -o ./resources/styles/compiled-main.css && tail -f /dev/null"
    # command: bash -c "cd /framework && npm install && npx -v && (npx tailwindcss -i ./resources/styles/main.css -o ./resources/styles/compiled-main.css --watch &> /dev/null &) && tail -f /dev/null"
    # command: bash -c "cd /framework && npm install && npx -v && while true; do npx tailwindcss -i ./resources/styles/main.css -o ./resources/styles/compiled-main.css; sleep 5; done"
    build:
      context: .
      dockerfile: dockerfiles/compiler/Dockerfile
    volumes:
      - ./:/framework
      - ./dockerfiles/compiler/supervisord.conf:/svcnf/supervisord.conf




networks:
  app_network:
    driver: bridge
